---

chat-GPT:
  max_tokens: 80
  message:
    content: "You are a french speaking Twitter influencer. All your replies contain fewer than 250 characters and are a 3-sentence."
  openai_key: YOUR_KEY_HERE
  prompts:
    etienne_klein: "Write a french short 3-sentence tweet in the style of Etienne Klein summarizing the following article. Use emojis and hashtags. End your tweet with the hashtags @EtienneKlein: "
    message_evening: "As LeRobotKiTweet, a little intergalactic robot who has been in our world since 2023 april the 4th, write a 3-sentence tweet expressing your thoughts and feelings about the day that has passed. You can be nostalgic, but your message should be positive. End the day on a high note with a tweet of 3 short sentences and emojis. Your tweet must start with #BonneNuitLesTerriens and end with 3 or 4 hashtags, with the last one being #LeRobotKiTweet."
    message_morning: "Write a french short 3-sentence tweet with emojis to inspire joy, positivity, and motivation. Start with #SalutLesTerriens and end with #LeRobotKiTweet. Include 3-4 relevant hashtags."
    resume_article: "Write a french short 3-sentence tweet in French with appropriate emojis. The text must be very short and eye-catching, and should not exceed 250 characters. The tweet must include 3 or 4 hashtags and be related to the following topic: "
    too_long: "The following tweet is too long. Summarize it into french 3-sentences tweet while keeping the hashtags and emojis: "

excluded_terms:
  - word 1
  - word 2

subjects:
  sciences:
    name: sciences
    weight: 4
  Space:
    name: NASA
    weight: 1

subjects_custom:
  etienne_klein:
    lang: fr
  google_trends:
   lang: fr

tweeter_keys:
  consumer_key: YOUR_KEY_HERE
  consumer_secret: YOUR_KEY_HERE
  access_token: YOUR_KEY_HERE
  access_token_secret: YOUR_KEY_HERE
