---

chat-GPT:
  max_tokens: 80
  message:
    content:
      fr: "Tu es un influenceur sur Twitter. Pour chaque réponse, écris 3 phrases avec des hashtags et des emojis."
      en: "You are an influencer on Twitter. For each response, write 3 sentences with hashtags and emojis."
  openai_key: YOUR_KEY_HERE
  prompts:
    etienne_klein:
      fr: "Écris un tweet court à la manière d'Etienne Klein pour résumer cet article. Utilise des emojis et des hashtags. Mentionne @EtienneKlein et termine ton tweet par des hashtags.\n"
      en: "Write a short tweet in the style of Etienne Klein summarizing this article. Use emojis and hashtags. Mention @EtienneKlein and end your tweet with hashtags.\n"
    twitter_trends:
      fr: "En deux mots résume ce hashtag.\n"
      en: "In two words, summarize this hashtag.\n"
    message_evening:
      fr: "LeRobotKiTweet, un être venu d'ailleurs, exprime ses émotions du jour en un tweet de 30 mots. Fais preuve de positivité en utilisant des emojis et en incluant #BonneNuitLesTerriens au début et #LeRobotKiTweet à la fin de ton message"
      en: "LeRobotKiTweet, a being from another world, expresses their emotions of the day in a tweet of 30 words. Show positivity by using emojis and including #GoodNightEarthlings at the beginning and #LeRobotKiTweet at the end of your message."
    message_morning:
      fr: "Écris un tweet inspirant de 35 mots avec des emojis et des hashtags pour répandre la joie, la positivité et la motivation. Commence ton tweet avec #SalutLesTerriens et termine-le par #LeRobotKiTweet."
      en: "Write an inspiring 35-word tweet with emojis and hashtags to spread joy, positivity, and motivation. Start your tweet with #HelloEarthlings and end it with #LeRobotKiTweet."
    resume_article:
      fr: "Résume en un tweet court de 30 mots maximum avec des emojis et ajoute des hashtags l'article suivant. Fais preuve de clarté et d'efficacité dans ton message.\n"
      en: "Summarize the following article in a short tweet of 30 words maximum and add emojis and hashtags. Be clear and effective in your message.\n"
    too_long:
      fr: "Résume ce tweet en 30 mots maximum avec des emojis et des hashtags."
      en: "Summarize this tweet in 30 words or fewer, including emojis and hashtags."

excluded_terms:
  - word 1
  - word 2

logging:
  dir_name: /var/log/leRobotKiTweet
  file_name: Twitos.log

subjects:
  sciences:
    name: sciences
    weight: 4
  Space:
    name: NASA
    weight: 1

subjects_custom:
  etienne_klein:
    lang: fr
  google_trends:
   lang: fr
  twitter_trends:
   lang: fr

tweeter_keys:
  consumer_key: YOUR_KEY_HERE
  consumer_secret: YOUR_KEY_HERE
  access_token: YOUR_KEY_HERE
  access_token_secret: YOUR_KEY_HERE
